# Generated by Django 3.1.2 on 2020-11-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibloguser',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vibloguser',
            name='biography',
            field=models.TextField(null=True),
        ),
    ]
