# Generated by Django 3.1.2 on 2020-11-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogs',
            new_name='blog',
        ),
    ]
